# Generated by Django 4.1.1 on 2022-09-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_unit_price_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
